// Generated by CoffeeScript 1.9.1
(function() {
  var base, base1, convertToSmartObject, deleteEmptyLayerSets, deleteEmptyLayers, main, rasterize, setup;

  if ((base = String.prototype).startsWith == null) {
    base.startsWith = function(s) {
      return this.slice(0, s.length) === s;
    };
  }

  if ((base1 = String.prototype).endsWith == null) {
    base1.endsWith = function(s) {
      return s === '' || this.slice(-s.length) === s;
    };
  }

  setup = function() {
    preferences.rulerUnits = Units.PIXELS;
    if (app.documents.length === 0) {
      alert('cannot access document');
      return false;
    }
    return true;
  };

  deleteEmptyLayers = function(root) {
    var deleteLayers, i, j, layer, len, len1, ref, results;
    deleteLayers = [];
    ref = root.artLayers;
    for (i = 0, len = ref.length; i < len; i++) {
      layer = ref[i];
      if (!layer.visible || layer.name.startsWith('#')) {
        deleteLayers.push(layer);
      }
    }
    results = [];
    for (j = 0, len1 = deleteLayers.length; j < len1; j++) {
      layer = deleteLayers[j];
      results.push(layer.remove());
    }
    return results;
  };

  deleteEmptyLayerSets = function(root) {
    var deleteLayerSets, i, j, layer, layerSet, len, len1, ref, results;
    deleteLayerSets = [];
    ref = root.layerSets;
    for (i = 0, len = ref.length; i < len; i++) {
      layerSet = ref[i];
      if (!layerSet.visible || layerSet.name.startsWith('#')) {
        deleteLayerSets.push(layerSet);
      }
    }
    results = [];
    for (j = 0, len1 = deleteLayerSets.length; j < len1; j++) {
      layer = deleteLayerSets[j];
      results.push(layer.remove());
    }
    return results;
  };

  convertToSmartObject = function(layer) {
    layer.allLocked = false;
    app.activeDocument.activeLayer = layer;
    return executeAction(app.stringIDToTypeID('newPlacedLayer'), new ActionDescriptor(), DialogModes.NO);
  };

  rasterize = function(root) {
    var i, j, k, layer, layerSet, len, len1, len2, ref, ref1, ref2, results;
    deleteEmptyLayers(root);
    deleteEmptyLayerSets(root);
    ref = root.artLayers;
    for (i = 0, len = ref.length; i < len; i++) {
      layer = ref[i];
      if (layer.kind === LayerKind.TEXT) {
        continue;
      }
      convertToSmartObject(layer);
    }
    ref1 = root.artLayers;
    for (j = 0, len1 = ref1.length; j < len1; j++) {
      layer = ref1[j];
      if (layer.kind === LayerKind.TEXT) {
        continue;
      }
      layer.rasterize(RasterizeType.ENTIRELAYER);
    }
    ref2 = root.layerSets;
    results = [];
    for (k = 0, len2 = ref2.length; k < len2; k++) {
      layerSet = ref2[k];
      results.push(rasterize(layerSet));
    }
    return results;
  };

  main = function() {
    var copiedDoc, docName, docPath;
    docName = activeDocument.name.slice(0, -4) + '.converted.psd';
    docName = docName.replace(/original.converted.psd/g, "psd");
    docPath = app.activeDocument.path;
    copiedDoc = app.activeDocument.duplicate(docName);
    rasterize(copiedDoc);
    return copiedDoc.saveAs(File(docPath + '/' + docName));
  };

  if (setup()) {
    main();
  }

}).call(this);
