// Generated by CoffeeScript 1.9.1
(function() {
  var main, rasterize, setup;

  setup = function() {
    preferences.rulerUnits = Units.PIXELS;
    if (app.documents.length === 0) {
      alert('cannot access document');
      return false;
    }
    return true;
  };

  rasterize = function(root) {
    var i, j, k, layer, layerSet, len, len1, len2, ref, ref1, ref2, results;
    ref = root.artLayers;
    for (i = 0, len = ref.length; i < len; i++) {
      layer = ref[i];
      if (layer.kind === LayerKind.TEXT || !layer.visible) {
        continue;
      }
      layer.allLocked = false;
      app.activeDocument.activeLayer = layer;
      executeAction(app.stringIDToTypeID('newPlacedLayer'), new ActionDescriptor(), DialogModes.NO);
    }
    ref1 = root.artLayers;
    for (j = 0, len1 = ref1.length; j < len1; j++) {
      layer = ref1[j];
      if (layer.kind === LayerKind.TEXT || !layer.visible) {
        continue;
      }
      layer.rasterize(RasterizeType.ENTIRELAYER);
    }
    ref2 = root.layerSets;
    results = [];
    for (k = 0, len2 = ref2.length; k < len2; k++) {
      layerSet = ref2[k];
      if (layerSet.visible) {
        results.push(rasterize(layerSet));
      } else {
        results.push(void 0);
      }
    }
    return results;
  };

  main = function() {
    var copiedDoc, docName, docPath;
    docName = activeDocument.name.slice(0, -4) + '.converted.psd';
    docName = docName.replace(/original.converted.psd/g, "psd");
    docPath = app.activeDocument.path;
    copiedDoc = app.activeDocument.duplicate(docName);
    rasterize(copiedDoc);
    return copiedDoc.saveAs(File(docPath + '/' + docName));
  };

  if (setup()) {
    main();
  }

}).call(this);
